// <auto-generated />
using System;
using EnterPrice_E_Commerece_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnterPrice_E_Commerece_System.Migrations
{
    [DbContext(typeof(EnterPriseContext))]
    [Migration("20260331031602_Sales-Orders_Migration")]
    partial class SalesOrders_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Brand", b =>
                {
                    b.Property<int>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandID"));

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandID");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandID = 1,
                            LogoUrl = "/images/brands/samsung.png",
                            Name = "Samsung"
                        },
                        new
                        {
                            BrandID = 2,
                            LogoUrl = "/images/brands/apple.png",
                            Name = "Apple"
                        },
                        new
                        {
                            BrandID = 3,
                            LogoUrl = "/images/brands/dell.png",
                            Name = "Dell"
                        },
                        new
                        {
                            BrandID = 4,
                            LogoUrl = "/images/brands/hp.png",
                            Name = "HP"
                        },
                        new
                        {
                            BrandID = 5,
                            LogoUrl = "/images/brands/nike.png",
                            Name = "Nike"
                        },
                        new
                        {
                            BrandID = 6,
                            LogoUrl = "/images/brands/adidas.png",
                            Name = "Adidas"
                        },
                        new
                        {
                            BrandID = 7,
                            LogoUrl = "/images/brands/lg.png",
                            Name = "LG"
                        },
                        new
                        {
                            BrandID = 8,
                            LogoUrl = "/images/brands/zara.png",
                            Name = "Zara"
                        });
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Description = "Modern devices and technologies",
                            Name = "Electronics"
                        },
                        new
                        {
                            CategoryID = 2,
                            Description = "Latest smartphones and tablets",
                            Name = "Mobiles & Tablets",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            CategoryID = 3,
                            Description = "Computers and hardware equipment",
                            Name = "Laptops & Computers",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            CategoryID = 4,
                            Description = "Clothing for all ages",
                            Name = "Fashion & Clothing"
                        },
                        new
                        {
                            CategoryID = 5,
                            Description = "T-shirts, shirts, and pants",
                            Name = "Men's Clothing",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            CategoryID = 6,
                            Description = "Gym equipment and sports apparel",
                            Name = "Sports Equipment",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            CategoryID = 7,
                            Description = "Refrigerators, washing machines, and TVs",
                            Name = "Home Appliances"
                        },
                        new
                        {
                            CategoryID = 8,
                            Description = "Novels, engineering, and computer science",
                            Name = "Books & Publications"
                        });
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Inventory_Module.Inventory", b =>
                {
                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.Property<int?>("ReorderLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.HasKey("ProductVariantId", "WarehouseId");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Inventory_Module.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierID"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Inventory_Module.Warehouse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Location = "5th Settlement, Industrial Zone",
                            Name = "Main Warehouse - Cairo"
                        },
                        new
                        {
                            ID = 2,
                            Location = "Nasr City, Makram Ebeid Ext.",
                            Name = "Logistics Center - Cairo"
                        },
                        new
                        {
                            ID = 3,
                            Location = "Zagazig, Belbeis Road",
                            Name = "Sharqia Distribution Center"
                        },
                        new
                        {
                            ID = 4,
                            Location = "Borg El Arab",
                            Name = "Alexandria Warehouse"
                        },
                        new
                        {
                            ID = 5,
                            Location = "Mansoura",
                            Name = "Delta Warehouse"
                        });
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BrandID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FK_ProductBrand")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductID");

                    b.HasIndex("FK_ProductBrand");

                    b.HasIndex(new[] { "BrandID" }, "IX_BrandID");

                    b.HasIndex(new[] { "CategoryID" }, "IX_CategoryID");

                    b.HasIndex(new[] { "Name" }, "IX_ProductName");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.ProductImage", b =>
                {
                    b.Property<int>("ProductImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductImageID"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ProductImageID");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.ProductVariant", b =>
                {
                    b.Property<int>("ProductVariantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductVariantID"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceAdjustment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductVariantID");

                    b.HasIndex("ProductID");

                    b.HasIndex(new[] { "SKU" }, "IX_SKU")
                        .IsUnique();

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Sales___Orders_Module.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Sales___Orders_Module.CartItem", b =>
                {
                    b.Property<int>("ProudctVariantID")
                        .HasColumnType("int");

                    b.Property<int>("CartID")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantID")
                        .HasColumnType("int");

                    b.Property<int>("Qunatity")
                        .HasColumnType("int");

                    b.HasKey("ProudctVariantID", "CartID");

                    b.HasIndex("CartID");

                    b.HasIndex("ProductVariantID");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Sales___Orders_Module.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Sales___Orders_Module.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CouponId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShippingAddressId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("ShippingAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Sales___Orders_Module.OrderItem", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID", "ProductVariantId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Sales___Orders_Module.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.UserModule.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.UserModule.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.UserModule.User", b =>
                {
                    b.Property<int>("USerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("USerID"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("USerID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUSerID")
                        .HasColumnType("int");

                    b.HasKey("RolesId", "UsersUSerID");

                    b.HasIndex("UsersUSerID");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Category", b =>
                {
                    b.HasOne("EnterPrice_E_Commerece_System.Entites.Category", "ParentCategory")
                        .WithMany("Categories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CategoryParent");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Inventory_Module.Inventory", b =>
                {
                    b.HasOne("EnterPrice_E_Commerece_System.Entites.ProductVariant", "ProductVariant")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Ineventory_ProductVarient");

                    b.HasOne("EnterPrice_E_Commerece_System.Entites.Inventory_Module.Warehouse", "Warehouse")
                        .WithMany("Inventories")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Warehouse_Inventory");

                    b.Navigation("ProductVariant");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Product", b =>
                {
                    b.HasOne("EnterPrice_E_Commerece_System.Entites.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Product_Category");

                    b.HasOne("EnterPrice_E_Commerece_System.Entites.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("FK_ProductBrand")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.ProductImage", b =>
                {
                    b.HasOne("EnterPrice_E_Commerece_System.Entites.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Product_ProductImage");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.ProductVariant", b =>
                {
                    b.HasOne("EnterPrice_E_Commerece_System.Entites.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Product_VarientProduct");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Sales___Orders_Module.Cart", b =>
                {
                    b.HasOne("EnterPrice_E_Commerece_System.Entites.UserModule.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("EnterPrice_E_Commerece_System.Entites.Sales___Orders_Module.Cart", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Sales___Orders_Module.CartItem", b =>
                {
                    b.HasOne("EnterPrice_E_Commerece_System.Entites.Sales___Orders_Module.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnterPrice_E_Commerece_System.Entites.ProductVariant", "ProductVariant")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductVariantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Sales___Orders_Module.Order", b =>
                {
                    b.HasOne("EnterPrice_E_Commerece_System.Entites.Sales___Orders_Module.Coupon", "Coupon")
                        .WithMany("Orders")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EnterPrice_E_Commerece_System.Entites.UserModule.Address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnterPrice_E_Commerece_System.Entites.UserModule.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Coupon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Sales___Orders_Module.OrderItem", b =>
                {
                    b.HasOne("EnterPrice_E_Commerece_System.Entites.Sales___Orders_Module.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnterPrice_E_Commerece_System.Entites.ProductVariant", "ProductVariant")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Sales___Orders_Module.Payment", b =>
                {
                    b.HasOne("EnterPrice_E_Commerece_System.Entites.Sales___Orders_Module.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("EnterPrice_E_Commerece_System.Entites.Sales___Orders_Module.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.UserModule.Address", b =>
                {
                    b.HasOne("EnterPrice_E_Commerece_System.Entites.UserModule.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("EnterPrice_E_Commerece_System.Entites.UserModule.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnterPrice_E_Commerece_System.Entites.UserModule.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUSerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Category", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Inventory_Module.Warehouse", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Product", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.ProductVariant", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Inventories");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Sales___Orders_Module.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Sales___Orders_Module.Coupon", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Sales___Orders_Module.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.UserModule.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.UserModule.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
