// <auto-generated />
using EnterPrice_E_Commerece_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnterPrice_E_Commerece_System.Migrations
{
    [DbContext(typeof(EnterPriseContext))]
    [Migration("20260326151411_InventoryModuleMigartion")]
    partial class InventoryModuleMigartion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Brand", b =>
                {
                    b.Property<int>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandID"));

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandID");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandID = 1,
                            LogoUrl = "/images/brands/samsung.png",
                            Name = "Samsung"
                        },
                        new
                        {
                            BrandID = 2,
                            LogoUrl = "/images/brands/apple.png",
                            Name = "Apple"
                        },
                        new
                        {
                            BrandID = 3,
                            LogoUrl = "/images/brands/dell.png",
                            Name = "Dell"
                        },
                        new
                        {
                            BrandID = 4,
                            LogoUrl = "/images/brands/hp.png",
                            Name = "HP"
                        },
                        new
                        {
                            BrandID = 5,
                            LogoUrl = "/images/brands/nike.png",
                            Name = "Nike"
                        },
                        new
                        {
                            BrandID = 6,
                            LogoUrl = "/images/brands/adidas.png",
                            Name = "Adidas"
                        },
                        new
                        {
                            BrandID = 7,
                            LogoUrl = "/images/brands/lg.png",
                            Name = "LG"
                        },
                        new
                        {
                            BrandID = 8,
                            LogoUrl = "/images/brands/zara.png",
                            Name = "Zara"
                        });
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Description = "Modern devices and technologies",
                            Name = "Electronics"
                        },
                        new
                        {
                            CategoryID = 2,
                            Description = "Latest smartphones and tablets",
                            Name = "Mobiles & Tablets",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            CategoryID = 3,
                            Description = "Computers and hardware equipment",
                            Name = "Laptops & Computers",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            CategoryID = 4,
                            Description = "Clothing for all ages",
                            Name = "Fashion & Clothing"
                        },
                        new
                        {
                            CategoryID = 5,
                            Description = "T-shirts, shirts, and pants",
                            Name = "Men's Clothing",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            CategoryID = 6,
                            Description = "Gym equipment and sports apparel",
                            Name = "Sports Equipment",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            CategoryID = 7,
                            Description = "Refrigerators, washing machines, and TVs",
                            Name = "Home Appliances"
                        },
                        new
                        {
                            CategoryID = 8,
                            Description = "Novels, engineering, and computer science",
                            Name = "Books & Publications"
                        });
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Inventory_Module.Inventory", b =>
                {
                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.Property<int?>("ReorderLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.HasKey("ProductVariantId", "WarehouseId");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Inventory_Module.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierID"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Inventory_Module.Warehouse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Location = "5th Settlement, Industrial Zone",
                            Name = "Main Warehouse - Cairo"
                        },
                        new
                        {
                            ID = 2,
                            Location = "Nasr City, Makram Ebeid Ext.",
                            Name = "Logistics Center - Cairo"
                        },
                        new
                        {
                            ID = 3,
                            Location = "Zagazig, Belbeis Road",
                            Name = "Sharqia Distribution Center"
                        },
                        new
                        {
                            ID = 4,
                            Location = "Borg El Arab",
                            Name = "Alexandria Warehouse"
                        },
                        new
                        {
                            ID = 5,
                            Location = "Mansoura",
                            Name = "Delta Warehouse"
                        });
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BrandID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FK_ProductBrand")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductID");

                    b.HasIndex("FK_ProductBrand");

                    b.HasIndex(new[] { "BrandID" }, "IX_BrandID");

                    b.HasIndex(new[] { "CategoryID" }, "IX_CategoryID");

                    b.HasIndex(new[] { "Name" }, "IX_ProductName");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.ProductImage", b =>
                {
                    b.Property<int>("ProductImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductImageID"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ProductImageID");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.ProductVariant", b =>
                {
                    b.Property<int>("ProductVariantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductVariantID"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceAdjustment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductVariantID");

                    b.HasIndex("ProductID");

                    b.HasIndex(new[] { "SKU" }, "IX_SKU");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Category", b =>
                {
                    b.HasOne("EnterPrice_E_Commerece_System.Entites.Category", "ParentCategory")
                        .WithMany("Categories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CategoryParent");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Inventory_Module.Inventory", b =>
                {
                    b.HasOne("EnterPrice_E_Commerece_System.Entites.ProductVariant", "ProductVariant")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Ineventory_ProductVarient");

                    b.HasOne("EnterPrice_E_Commerece_System.Entites.Inventory_Module.Warehouse", "Warehouse")
                        .WithMany("Inventories")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Warehouse_Inventory");

                    b.Navigation("ProductVariant");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Product", b =>
                {
                    b.HasOne("EnterPrice_E_Commerece_System.Entites.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Product_Category");

                    b.HasOne("EnterPrice_E_Commerece_System.Entites.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("FK_ProductBrand")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.ProductImage", b =>
                {
                    b.HasOne("EnterPrice_E_Commerece_System.Entites.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Product_ProductImage");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.ProductVariant", b =>
                {
                    b.HasOne("EnterPrice_E_Commerece_System.Entites.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Product_VarientProduct");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Category", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Inventory_Module.Warehouse", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.Product", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("EnterPrice_E_Commerece_System.Entites.ProductVariant", b =>
                {
                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
